possible bugfix for session handling
broadinstitute/import-service pull request #66
Opened 2021-09-04 17:32 UTC by helgridly

Hey folks. I still crib from import-service when I'm working on a Python project and I think I've noticed a mistake here. SQLAlchemy's `sessionmaker` is a session factory. Its intended usage is something like:

```
sessionmaker = sqlalchemy.orm.sessionmaker(bind=_db, ...blah blah...)

 # now get some sessions (imagine this is being called from other code)
session1 = sessionmaker()
session2 = sessionmaker()
```

Import service's code for `get_session()` is creating a sessionmaker every single time it's called. It's (probably) not going to cause any problems, but it only needs to be constructed once. This PR does that by creating the sessionmaker alongside the db engine singleton.

Obviously I haven't tested it on GAE etc. Hope y'all are well!

2021-10-17 16:33 UTC, davidangb approved these changes
thank you!

2021-10-17 16:42 UTC, davidangb requested changes
see #68, where we can get full tests running. Blocking merge until that other PR shows green …

2021-10-18 14:24 UTC, davidangb commented
@helgridly thanks again for this PR, and … good to hear from you!! See https://github.com/broadinstitute/import-service/pull/68/commits/52e89781364491ea7d85b4352133c86d2be8a35c … lots of tests are failing without this change. Do you want to incorporate that into this PR so it's your commit? I could also just merge #68.

2021-10-18 14:39 UTC, helgridly commented
Huh. With `_db` and `_sessionmaker` assigned in the same block, I don't understand why one would be `None` and not the other. But maybe there's some nuance to the GAE caching I'm missing.

In any case - go ahead and do whatever needs to be done to make this work for you. I'm not attached to having my name on the commit :)

2021-10-28 16:10 UTC, davidangb commented
I've merged #68; this PR is now obsolete. Thank you again! Feel free to close; I'll close it myself in a few days if you don't see this.

2021-12-01 14:26 UTC, closed without merging